### ISSUE TITLE
missing directory

### ISSUE THREAD

**Issue by johnwalkervinest** [newcrossfoodcoop/nxfc#1]
@bsimpson53 Help.
The Vagrantfile specifies /nxfc-mongo, but I can't find this directory anywhere

**Comment by johnwalkervinest** [comment]
Solved now. I learned that I needed the latest version of vagrant

**Comment by bsimpson53** [comment]
Hey John,

Sorry I missed your message last night.

The local version should be working now although I was making changes last night and it was definitely broken yesterday.

Right now mongo seems to be broken for production :(

**Comment by johnwalkervinest** [comment]
I am enjoying learning all this!
Signed up and wrote some articles. Can chat to myself.
I have been playing with mongo, the shell where I can do queries.

**Comment by bsimpson53** [comment]
Feel free to add anything you feel is useful to the wiki :)

I'm going to open some issues over the next few days for different bits that need to be done
