### ISSUE TITLE
Ingest from Suma into products module

### ISSUE THREAD

**Issue by bsimpson53** [newcrossfoodcoop/nxfc#4]
### Products module
* Simple CRUD module
* 2 types of product
    * manual: can be edited admins
    * ingested: can't be edited admins

### Suma Ingest
Admin:
1. uploads a csv via web interface
2. server validates format, activates ingest button
3. clicks on ingest, summary displayed on completion, activates publish button
4. clicks publish button, products become visible to all users

### Assets
* http://www.suma.coop/download-links-3 (contact @bsimpson53 for password)

**Comment by pomdyer** [comment]
Hi @bsimpson53.

I tried to create products module via  "yo meanjs:crud-module products" command but I can't get the web service started but I ended up in this line:

==> web: Provisioners will not be run since container doesn't support SSH.

What I have done wrong?

**Comment by bsimpson53** [comment]
That comes up anyway, is just a vagrant warning, it starts the container
anyway.

If you do 'vagrant docker-logs -f web' it should tail the logs for you.
There may be some other reason that it's not started.

I'm not sure if the yo generator works with the version of mean we're using
though. I'd be keen to find out if it does.

Ben

**Comment by bsimpson53** [comment]
Hi @pomdyer,

Did you get any further with this one?
