### ISSUE TITLE
User Managment

### ISSUE THREAD

**Issue by bsimpson53** [newcrossfoodcoop/nxfc#5]
We will start with three types of users:
* basic
* admin
* super

There are acl features built into the codebase but it's not clear how they should be used.

Basics should:
* not be able to see Users menu

Admins should:
* be able to see users

Supers should:
* be able to make a user an admin

**Comment by bsimpson53** [comment]
Looks like acl is integrated already via ```modules/*/server/policies/*.js```

The example in the articles file looks fairly workable...

**Comment by johnwalkervinest** [comment]
I'll have a look at this to see if I can understand it.

**Comment by johnwalkervinest** [comment]
I am trying to build a simple admin interface. It lets you add users.  It is the menus I am still struggling with.

**Comment by bsimpson53** [comment]
I think that much of this may already exist. Have you had a look at the
user module policy file, I think giving your user the admin role may expose
extra functionality.

**Comment by bsimpson53** [comment]
I've implemented something basic here, users can be listed and edited by 'admin' users.
